"""created the columns for the messages table 

Revision ID: 63c3fe4ab16e
Revises: d077cc99a5b6
Create Date: 2023-09-21 18:34:01.201327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c3fe4ab16e'
down_revision = 'd077cc99a5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('body')

    # ### end Alembic commands ###
